# Generated by Django 2.0.5 on 2018-05-30 13:39

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
