# Generated by Django 2.0.5 on 2018-05-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
    ]
